### PR TITLE
Add "Get videos from channel" functionality.

### PR DESCRIPTION
**Pull request by AlexNik**
I've added new functionality for downloading video from channel and make some refactoring.
@VasiliPupkin256 @novitae could you review this?
изображение

### CODE REVIEW

**Comment by VasiliPupkin256** [comment]
Could `get_stories` also generalized this way?

**Comment by AlexNik** [comment]
> Could `get_stories` also generalized this way?

Quick answer - no.
There is speciefic logic for getting stories URLs.
I could try to use common code for stories but it will be more complex refactoring...

**Comment by novitae** [comment]
> @VasiliPupkin256 @novitae could you review this?

you @ed me but I can't review (or im just dumb, I never did this before idk)

**Comment by VasiliPupkin256** [comment]
Does it require an explicit action? If it is tested and works well then I am ok with that of course

**Comment by AlexNik** [comment]
@VasiliPupkin256 What do you mean "explicit action"?
I've tested with 3 accounts, I can't say that it is good testing))
If anyone could test it more deeper and give some feedback it wold be great.

**Pull request closed without merging**
